"""
Django settings for job_buddy project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Setting up Django Environ 
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-je73tfk#)daqx&$vlzm+=b27)!=7o6-@a892eo0fpn^9_r%6b5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Default applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My Applications,
    'job_buddy_app',
    'job_buddy_users',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'djoser',
    'storages',

]

MIDDLEWARE = [
    # Make sure corsheaders is first 
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'job_buddy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'job_buddy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('LOCAL_DB_NAME'),
        'USER': env('LOCAL_DB_USER'),
        'PASSWORD': env('LOCAL_DB_PASSWORD'),
        'HOST': env('LOCAL_DB_HOST'),
        'PORT': env('LOCAL_DB_PORT'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / "db.sqlite3",  # Using BASE_DIR to point to the database file
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# # Static files (CSS, JavaScript, Images) LOCAL
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Corsheaders
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://localhost:3000',
)

# # Media Files LOCAL
# MEDIA_URL = '/uploads/'
# MEDIA_ROOT = os.path.join(BASE_DIR,'job_buddy_app/static')

# Django SWT Authentication System
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # During Api requests, we use SJWT
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Enable session-based and basic auth for the browsable API
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

# We're not using Sliding Tokens because this isn't a session based application.
# We want our users to be logged throughout days 
#
# We're using Rotate Tokens for extra security because when issuing a new Access Token we'll get a new refresh token
# However, the lifespan will remain the same
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Short lifetime for security
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token allows users to get new access tokens
    'ROTATE_REFRESH_TOKENS': True,  # Refresh token rotates upon use for added security
    'BLACKLIST_AFTER_ROTATION': True,  # Ensures old refresh tokens can't be reused
}

DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '/activate/{uid}/{token}', # We just need to make sure this is sent to the front end page 
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SEND_ACTIVATION_EMAIL': True,
}

# Custom User Model 
AUTH_USER_MODEL = 'job_buddy_users.JobBuddyUser'

# Email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('JB_EMAIL_HOST') 
EMAIL_PORT = 587  # Port for TLS
EMAIL_USE_TLS = True  # Use TLS
EMAIL_HOST_USER = env('JB_EMAIL_HOST_USER')  
EMAIL_HOST_PASSWORD = env('JB_EMAIL_HOST_PASSWORD') 

# Django S3 Bucket 
# AWS_ACCESS_KEY_ID = env('JB_AWS_ACCESS_KEY')
# AWS_SECRET_ACCESS_KEY = env('JB_AWS_SECRET_KEY')
# AWS_STORAGE_BUCKET_NAME = env('JB_AWS_BUCKET_NAME')
# AWS_DEFAULT_ACL = 'public-read'
# # For Media Files
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# # For Static Files
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# # AWS_S3_SIGNATURE_VERSION = 's3v4'
# AWS_S3_FILE_UPLOAD_MAX_SIZE = 10485760  # Example: 10 MB max

# # Static and Media files Boto3 Storage
# MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/uploads/'  # Update with your bucket's URL
# MEDIA_ROOT = os.path.join(BASE_DIR,'job_buddy_app/media')
# STATIC_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/static/'  # Update with your bucket's URL

# AWS S3 Bucket Configurations
AWS_ACCESS_KEY_ID = env('JB_AWS_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = env('JB_AWS_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = env('JB_AWS_BUCKET_NAME')
AWS_S3_REGION_NAME = 'us-east-1'  # No leading space before region name

# S3 static and media file settings
AWS_S3_FILE_OVERWRITE = False 
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

MEDIA_URL = 'media/'
STATIC_URL = 'staticfiles/'

# FIX: Django 4.2 >
STORAGES={
        # Media Files 
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        # CSS and JS file management
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        }
}