# Generated by Django 5.1.1 on 2024-10-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_buddy_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobbuddyuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
