# Generated by Django 5.1.1 on 2024-09-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=80)),
                ('salary', models.IntegerField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=35)),
            ],
        ),
    ]
