# Generated by Django 5.1.1 on 2024-10-01 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=35),
        ),
        migrations.CreateModel(
            name='JobImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_img', models.ImageField(upload_to='job_img/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_buddy_app.job')),
            ],
        ),
    ]
