# Generated by Django 5.1.1 on 2024-10-02 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_buddy_app', '0002_alter_job_status_jobimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobimages',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_images', to='job_buddy_app.job'),
        ),
    ]
