# Generated by Django 5.1.1 on 2024-10-04 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_buddy_app', '0004_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
