# Generated by Django 5.1.1 on 2024-10-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_buddy_app', '0006_job_job_city_job_job_link_job_job_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimages',
            name='job_img_resized',
            field=models.ImageField(blank=True, null=True, upload_to='job_img_resized/'),
        ),
    ]
